// <auto-generated />
using System;
using Cargo_Management_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cargo_Management_Project.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260716124235_UpdateTrackingModels")]
    partial class UpdateTrackingModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cargo_Management_Project.Models.CargoEvent", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<int>("ContainerId")
                        .HasColumnType("int");

                    b.Property<string>("EventLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EventTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("EventId");

                    b.HasIndex("ContainerId");

                    b.ToTable("CargoEvents");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            ContainerId = 1,
                            EventLocation = "Port of Shanghai",
                            EventTimestamp = new DateTime(2026, 7, 10, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            EventType = 1,
                            Remarks = "Loaded securely on vessel."
                        });
                });

            modelBuilder.Entity("Cargo_Management_Project.Models.Container", b =>
                {
                    b.Property<int>("ContainerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContainerId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("ContainerNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContainerStatus")
                        .HasColumnType("int");

                    b.Property<int>("ContainerType")
                        .HasColumnType("int");

                    b.Property<string>("SealNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContainerId");

                    b.HasIndex("BookingId");

                    b.ToTable("Containers");

                    b.HasData(
                        new
                        {
                            ContainerId = 1,
                            BookingId = 1,
                            ContainerNumber = "CONT-998877",
                            ContainerStatus = 1,
                            ContainerType = 0,
                            SealNumber = "SEAL-XYZ123"
                        });
                });

            modelBuilder.Entity("Cargo_Management_Project.Models.CustomsDeclaration", b =>
                {
                    b.Property<int>("DeclarationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeclarationId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<decimal>("CalculatedDuty")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("ClearanceStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("DeclaredValue")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("HsCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeclarationId");

                    b.HasIndex("BookingId");

                    b.ToTable("CustomsDeclarations");

                    b.HasData(
                        new
                        {
                            DeclarationId = 1,
                            BookingId = 1,
                            CalculatedDuty = 2500.00m,
                            ClearanceStatus = 2,
                            DeclaredValue = 50000.00m,
                            HsCode = "8471.30.00"
                        });
                });

            modelBuilder.Entity("Cargo_Management_Project.Models.FreightInvoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("FreightCharges")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("InvoiceStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("SurchargeAmount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("InvoiceId");

                    b.HasIndex("BookingId");

                    b.ToTable("FreightInvoices");

                    b.HasData(
                        new
                        {
                            InvoiceId = 1,
                            BookingId = 1,
                            Currency = "USD",
                            FreightCharges = 3500.00m,
                            InvoiceStatus = 2,
                            SurchargeAmount = 500.00m,
                            TotalAmount = 4000.00m
                        });
                });

            modelBuilder.Entity("Cargo_Management_Project.Models.ShipmentBooking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<string>("BookingNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("BookingStatus")
                        .HasColumnType("int");

                    b.Property<string>("ConsigneeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DestinationPort")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OriginPort")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShipperName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BookingId");

                    b.ToTable("ShipmentBookings");

                    b.HasData(
                        new
                        {
                            BookingId = 1,
                            BookingNumber = "BKG-2026-001",
                            BookingStatus = 3,
                            ConsigneeName = "Euro Imports Ltd",
                            DestinationPort = "Rotterdam",
                            OriginPort = "Shanghai",
                            ShipperName = "Global Tech Exports"
                        });
                });

            modelBuilder.Entity("Cargo_Management_Project.Models.CargoEvent", b =>
                {
                    b.HasOne("Cargo_Management_Project.Models.Container", "Container")
                        .WithMany("CargoEvents")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");
                });

            modelBuilder.Entity("Cargo_Management_Project.Models.Container", b =>
                {
                    b.HasOne("Cargo_Management_Project.Models.ShipmentBooking", "ShipmentBooking")
                        .WithMany("Containers")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShipmentBooking");
                });

            modelBuilder.Entity("Cargo_Management_Project.Models.CustomsDeclaration", b =>
                {
                    b.HasOne("Cargo_Management_Project.Models.ShipmentBooking", "ShipmentBooking")
                        .WithMany("CustomsDeclarations")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShipmentBooking");
                });

            modelBuilder.Entity("Cargo_Management_Project.Models.FreightInvoice", b =>
                {
                    b.HasOne("Cargo_Management_Project.Models.ShipmentBooking", "ShipmentBooking")
                        .WithMany("FreightInvoices")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShipmentBooking");
                });

            modelBuilder.Entity("Cargo_Management_Project.Models.Container", b =>
                {
                    b.Navigation("CargoEvents");
                });

            modelBuilder.Entity("Cargo_Management_Project.Models.ShipmentBooking", b =>
                {
                    b.Navigation("Containers");

                    b.Navigation("CustomsDeclarations");

                    b.Navigation("FreightInvoices");
                });
#pragma warning restore 612, 618
        }
    }
}
